name: validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ARTIFACTS/src/requirements.txt
          pip install jsonschema
      - name: Run tests
        run: |
          PYTHONPATH=ARTIFACTS/src pytest -q ARTIFACTS/tests
      - name: Validate docs
        run: |
          python VALIDATION/verify_docs.py
